[package]
name = "my-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "run01"
path = "src/run01.rs"

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
