# docker-compose.yaml
version: "3"

services:
  react-web:
    image: registry.cn-shanghai.aliyuncs.com/d2jvkpn/react-web:${TAG}
    container_name: react-web_${APP_ENV}
    restart: always
    # network_mode: bridge
    networks: ["net"]
    ports: ["${PORT}:80"]
    environment:
    - TZ="Asia/Shanghai"
    - NGINX_PORT=80

networks:
  net:
    name: react-web_${APP_ENV}
    driver: bridge
    external: false
