project: golang_postgres-redis
repository: https://github.com/d2jvkpn/exercises
version: 0.1.0

config: |
  # path: configs/{{.APP_ENV}}.yaml
  database:
    dsn: postgresql://hello:world@localhost:5432/simple_bank?sslmode=disable
  #
  redis:
    addr: localhost:6379
    password: world
    db: 0

.env:
  # content of .env
  export DATABASE_URL=postgresql://hello:world@localhost:5432/simple_bank?sslmode=disable
