[package]
name = "ch01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "ch01"

[[bin]]
name = "second"
path = "src/second.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
