---
- name: a02 reboot
  hosts: all
  become: true
  vars:
    # work_path: "/root"
    _wd: "{{lookup('env', 'PWD')}}"
    _hd: "{{lookup('env', 'HOME')}}"

  tasks:
  - name: reboot host(s)
    reboot:
      reboot_timeout: 600
      msg: "reboot by ansible"
      pre_reboot_delay: 5
      post_reboot_delay: 10
      test_command: whoami
      boot_time_command: cat /proc/sys/kernel/random/boot_id

  - name: check uptime
    command: uptime
    register: uptime_output

  - name: uptime output
    debug:
      var: uptime_output.stdout_lines
