# allow pods connect to an external services: external-ip:3306
apiVersion: v1
kind: Service
metadata:
   name: external-ip
   namespace: dev
spec:
   type: ClusterIP
   ports:
   - { protocol: TCP, name: mysql, port: 3306, targetPort: 3306 }
   - { protocol: TCP, name: xxxx,  port: 8000, targetPort: 8000 }
   - { protocol: TCP, name: postgres, port: 5432, targetPort: 5432 }

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip
  namespace: dev
subsets:
  - addresses:
    # localhost ip or the serivce ip
    - ip: 10.0.4.7
    ports:
    - { name: mysql, port: 3306 }
    - { name: xxxx,  port: 8000 }
    - { name: postgres, port: 5432 }

# $ kubectl exec -it PODNAME -- sh
# $ curl external-ip:8000
# $ nc -zv external-ip 8000

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: external-ip
spec:
  rules:
  - host: postgres.localdev.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: external-ip
            port:
              number: 5432

# psql --username postgres --host postgres.localdev.me --port 5432 --password postgres
