# allow pods connect to an external services: local-srv:5432
apiVersion: v1
kind: Service
metadata:
   name: local-srv
   namespace: dev
spec:
   type: ClusterIP
   ports:
   - { protocol: TCP, name: mysql, port: 3306, targetPort: 3306 }
   - { protocol: TCP, name: postgres, port: 5432, targetPort: 5432 }

---
apiVersion: v1
kind: Endpoints
metadata:
  name: local-srv
  namespace: dev
subsets:
  - addresses:
    # localhost ip or the serivce ip
    - ip: 127.0.0.1
    ports:
    - { name: mysql, port: 3306 }
    - { name: postgres, port: 5432 }

# $ kubectl exec -it PODNAME -- sh
# $ curl local-srv:5432
# $ nc -zv local-srv 5432
