# Dockerfile
#FROM node:lts-alpine AS builder
FROM node:22-alpine AS builder


ARG APP_Name
ARG APP_Version
ARG BASE_Path
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=build

#SHELL ["/bin/bash", "-c"]

WORKDIR /opt

RUN echo "==> BASE_Path: ${BASE_Path}"

ADD *.js *.json *.ts index.html ./
COPY public/ ./public
COPY src/ ./src

ADD target/env ./.env
COPY node_modules node_modules

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    npm config set registry https://registry.npmmirror.com; \
  fi

# npm install --registry=https://registry.npmmirror.com &> /dev/null
RUN npm install && npm run build -- --base=${BASE_Path} --outDir=target/dist${BASE_Path}

ADD target/build.yaml ./target/
ADD target/build.json ./target/dist$BASE_Path/

####
FROM nginx:1-alpine

ARG APP_Name
ARG APP_Version
ARG BASE_Path

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>
LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=running

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

WORKDIR /opt

RUN mkdir -p logs
COPY --from=builder /opt/target ./target
COPY static/ ./opt/dist/static

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bk
# sed -i '/worker_processes/s#auto#4#' /etc/nginx/nginx.conf

COPY deploy/default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
#CMD ["nginx", "-c", "/etc/nginx/conf.d/default.conf", "-g", "daemon off;"]
