apiVersion: v1
kind: Service

metadata:
  name: hello-nodeport
  labels:
    run: hello

spec:
  type: NodePort
  selector: { app: hello }

  ports:
  - { protocol: TCP, targetPort: 8080, port: 1024, nodePort: 30011 }
