global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'service'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
    - targets: ['localhost:8080']
