# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval:     30s
  scrape_timeout:      10s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 1m
  static_configs:
  - targets: ['localhost:9090']
  # - targets: ['prometheus:9090']

- job_name: 'node'
  static_configs:
  - targets: ['node-exporter:9100']

# https://prometheus.io/docs/practices/remote_write/
#remote_write:
#- url: '<Your Prometheus remote_write endpoint>'
#  basic_auth:
#    username: '<Your Grafana Username>'
#    password: '<Your Grafana API key>'

- job_name: app-api_dev
  metrics_path: /prometheus
  static_configs:
  - targets: ['app-api_dev:4002']
