// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.21.2
// source: pkg/greet/greet.proto

package greet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiceClient interface {
	// unary
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	// server streaming
	GreetStream(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetStreamClient, error)
	// client streaming
	Multiply(ctx context.Context, opts ...grpc.CallOption) (GreetService_MultiplyClient, error)
	// client and server streaming
	Hello(ctx context.Context, opts ...grpc.CallOption) (GreetService_HelloClient, error)
	// pending, in_progress, success, failed
	Upload(ctx context.Context, opts ...grpc.CallOption) (GreetService_UploadClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetStream(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[0], "/greet.GreetService/GreetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetStreamClient interface {
	Recv() (*GreetResponse, error)
	grpc.ClientStream
}

type greetServiceGreetStreamClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetStreamClient) Recv() (*GreetResponse, error) {
	m := new(GreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) Multiply(ctx context.Context, opts ...grpc.CallOption) (GreetService_MultiplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[1], "/greet.GreetService/Multiply", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceMultiplyClient{stream}
	return x, nil
}

type GreetService_MultiplyClient interface {
	Send(*Number) error
	CloseAndRecv() (*Number, error)
	grpc.ClientStream
}

type greetServiceMultiplyClient struct {
	grpc.ClientStream
}

func (x *greetServiceMultiplyClient) Send(m *Number) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceMultiplyClient) CloseAndRecv() (*Number, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Number)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) Hello(ctx context.Context, opts ...grpc.CallOption) (GreetService_HelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[2], "/greet.GreetService/Hello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceHelloClient{stream}
	return x, nil
}

type GreetService_HelloClient interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ClientStream
}

type greetServiceHelloClient struct {
	grpc.ClientStream
}

func (x *greetServiceHelloClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceHelloClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (GreetService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[3], "/greet.GreetService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceUploadClient{stream}
	return x, nil
}

type GreetService_UploadClient interface {
	Send(*File) error
	Recv() (*Msg, error)
	grpc.ClientStream
}

type greetServiceUploadClient struct {
	grpc.ClientStream
}

func (x *greetServiceUploadClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceUploadClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility
type GreetServiceServer interface {
	// unary
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	// server streaming
	GreetStream(*GreetRequest, GreetService_GreetStreamServer) error
	// client streaming
	Multiply(GreetService_MultiplyServer) error
	// client and server streaming
	Hello(GreetService_HelloServer) error
	// pending, in_progress, success, failed
	Upload(GreetService_UploadServer) error
	// mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (UnimplementedGreetServiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedGreetServiceServer) GreetStream(*GreetRequest, GreetService_GreetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetStream not implemented")
}
func (UnimplementedGreetServiceServer) Multiply(GreetService_MultiplyServer) error {
	return status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedGreetServiceServer) Hello(GreetService_HelloServer) error {
	return status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGreetServiceServer) Upload(GreetService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	// mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s grpc.ServiceRegistrar, srv GreetServiceServer) {
	s.RegisterService(&GreetService_ServiceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetStream(m, &greetServiceGreetStreamServer{stream})
}

type GreetService_GreetStreamServer interface {
	Send(*GreetResponse) error
	grpc.ServerStream
}

type greetServiceGreetStreamServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetStreamServer) Send(m *GreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_Multiply_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).Multiply(&greetServiceMultiplyServer{stream})
}

type GreetService_MultiplyServer interface {
	SendAndClose(*Number) error
	Recv() (*Number, error)
	grpc.ServerStream
}

type greetServiceMultiplyServer struct {
	grpc.ServerStream
}

func (x *greetServiceMultiplyServer) SendAndClose(m *Number) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceMultiplyServer) Recv() (*Number, error) {
	m := new(Number)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_Hello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).Hello(&greetServiceHelloServer{stream})
}

type GreetService_HelloServer interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type greetServiceHelloServer struct {
	grpc.ServerStream
}

func (x *greetServiceHelloServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceHelloServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).Upload(&greetServiceUploadServer{stream})
}

type GreetService_UploadServer interface {
	Send(*Msg) error
	Recv() (*File, error)
	grpc.ServerStream
}

type greetServiceUploadServer struct {
	grpc.ServerStream
}

func (x *greetServiceUploadServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceUploadServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetService_ServiceDesc is the grpc.ServiceDesc for GreetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetStream",
			Handler:       _GreetService_GreetStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Multiply",
			Handler:       _GreetService_Multiply_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Hello",
			Handler:       _GreetService_Hello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _GreetService_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/greet/greet.proto",
}
