[package]
name = "auth_service"
version = "0.1.0"
edition = "2021"
description = "Example auth services"
license = "GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
utils = { path = "../utils" }
