[package]
name = "a10_async"
version = "0.1.0"
edition = "2021"

default-run = "a10_async"

[[bin]]
name = "c01"
path = "bin/c01.rs"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.8", features = ["socks"] }
tokio = { version = "1.40.0", features = ["full"] }
