[package]
name = "procedural"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
chrono = "0.4"
darling = "0.20"
quote = "1"
syn = { version = "1", features = ["full"] }
